// 服务进度查询列表
export const CHANGE_TAB = 'CHANGE_TAB';
export const CATE_GORY = 'CATE_GORY';
export const CONTENT_LIST = 'CONTENT_LIST';
export const CONTENT_ORDER = 'CONTENT_ORDER';
export const SORT_CHANGE_TAB = 'SORT_CHANGE_TAB';
export const GET_FILTER_DATA = 'GET_FILTER_DATA';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const GET_LIST_DATA = 'GET_LIST_DATA';
export const MENU_GET_LIST_DATA = 'MENU_GET_LIST_DATA';
export const MENU_LEFT_CLICK = 'MENU_LEFT_CLICK';
export const ADD_SELECT_ITEM = 'ADD_SELECT_ITEM';
export const MINUS_SELECT_ITEM = 'MINUS_SELECT_ITEM';
export const SHOW_CHOOSE_COUNTENT = 'SHOW_CHOOSE_COUNTENT';
export const CLEAR_CAR = 'CLEAR_CAR';
export const COMMENT_LIST_DATA = 'COMMENT_LIST_DATA';
export const RESTANURANT_DATA = 'RESTANURANT_DATA';
